In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(1000)
%timeit [i**2 for i in l]

149 μs ± 19.5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

5.77 μs ± 690 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#creating array


In [6]:
a=np.array([1,2,3,4])

In [7]:
print(a.ndim)

1


In [8]:
b=np.array ([[1,2,3,4],[5,6,7,8]])
print(b.ndim)

2


In [9]:
c=np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
             
             

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(a.shape)

(4,)


In [11]:
print(b.shape)

(2, 4)


In [12]:
print(c.shape)

(2, 2, 2)


In [13]:
#creating functional array

In [14]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


# using linespace

In [16]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [17]:
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [18]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


a=np.zeros((5,5))
print(a)

In [19]:


a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
a=np.diag((1,2,3,4))
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
#basic data type

In [22]:
a=np.arange(10)
print(a.dtype)

int64


In [23]:
a=np.arange(10,dtype="float64")
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [24]:
print(a.dtype)

float64


#other data types

In [25]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [26]:
a=np.array([True,False])
print(a.dtype)

bool


In [27]:
a=np.array(["lokesh","kumar"])
print(a.dtype)

<U6


# indexing and slicing

In [28]:
a=np.arange(10)
print(a[5])


5


In [29]:
a=np.arange(2,20,2)
print(a[2])

6


In [30]:
a=np.diag([1,2,3])
print(a[2,2])


3


In [31]:
a[2,1] =5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# slicing

In [32]:
a= np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(a[1:8:1])

[1 2 3 4 5 6 7]


In [34]:
print(a[2:5:2])

[2 4]


# copies and viewing


In [35]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [36]:
print(np.shares_memory(a,b))

True


In [37]:
b[0]=5
print(a)
print(b)

[5 1 2 3 4 5 6 7 8 9]
[5 2 4 6 8]


In [38]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [39]:
print(np.shares_memory(a,b))

False


In [40]:
b[0]=10
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random number generator

In [41]:
a=np.random.randint(0,9,4)
print(a)

[5 6 8 5]


# ELEMENT WISE OPERATIONS

## 1.basic operations

In [42]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [43]:
print(a**2) #spuare

[ 1  4  9 16]


# all arthimatic operates Elementwise

In [44]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [45]:
print(a*b)

[2. 4. 6. 8.]


# comparision operator

In [46]:
a=np.array([1,2,3,4])
b=np.array([5,2,3,7])
print(a==b)

[False  True  True False]


In [47]:
print(a<b)

[ True False False  True]


In [48]:
print(a>b)

[False False False False]


In [49]:
print(a|b)

[5 2 3 7]


## array wise comparisrion

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [51]:
print(np.array_equal(a,c))

True


# logical operator

In [52]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([0,1,1,0],dtype="bool")


In [53]:
print(np.logical_or(a,b))

[ True  True  True False]


In [54]:
print(np.logical_and(a,b))

[False False  True False]


# Trigonometry /Transcendental Functtion

In [55]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [56]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [57]:
print(np.cos(a))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [58]:
print(np.tan(a))

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


In [59]:
print(np.log(a))

[      -inf 0.         0.69314718 1.09861229 1.38629436]


C:\Users\chede\AppData\Local\Temp\ipykernel_10812\897204776.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [60]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


# basic Reductions

In [61]:
x=np.array([1,2,3,4])
print(np.sum(x))


10


In [62]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [63]:
x.sum(axis=0)

array([2, 4])

In [64]:
x.sum(axis=1)

array([3, 3])

# other Reduction

In [65]:
x=np.array([1,2,3,4])
print(x.min())

1


In [66]:
print(x.max())

4


In [67]:
print(x.argmin())

0


In [68]:
print(x.argmax())

3


# pandaas

In [69]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [70]:
import pandas as pd
pd.__version__

'3.0.3'

## pandas data structure

### series -one dimentional column

### data-- table with rows + columns

In [71]:
import pandas as pd
s=pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64


In [72]:
df=pd.DataFrame({
    "name":["lokesh","kumar"],
    "age":[20,21]
})
df

,name,age
0,lokesh,20
1,kumar,21


### read csv

In [73]:
df=pd.read_csv("L:\student.csv")
df

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\chede\AppData\Local\Temp\ipykernel_10812\3246763598.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df=pd.read_csv("L:\student.csv")


,ID,Name,Age,City,Course
0,1,Rahul,21,Hyderabad,Python
1,2,Priya,20,Vijayawada,Java
2,3,Arjun,22,Guntur,Data Science
3,4,Sneha,19,Visakhapatnam,AI
4,5,Kiran,23,Tirupati,Python
5,6,Divya,21,Nellore,Java
6,7,Rakesh,20,Kurnool,Web Development
7,8,Anjali,22,Warangal,Data Science
8,9,Vamsi,24,Hyderabad,AI
9,10,Keerthi,21,Ongole,Python


In [88]:
df=pd.read_csv("L:\weather_data.csv")
df

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\chede\AppData\Local\Temp\ipykernel_10812\3987804041.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df=pd.read_csv("L:\weather_data.csv")


,Date,City,Temperature_C,Humidity_%,Condition
0,01-01-2025,Hyderbad,28.0,60.0,Sunny
1,02-01-2025,Vijayawada,29.0,62.0,Sunny
2,03-01-2025,Viskhapatnam,NaN,58.0,Cloudy
3,04-01-2025,Kakinada,31.0,55.0,Cloudy
4,05-01-2025,Banglore,NaN,57.0,Rainy
5,06-01-2025,Mumbai,33.0,NaN,Rainy
6,07-01-2025,Chennai,34.0,61.0,Sunny
7,08-01-2025,Rajamundry,32.0,63.0,Cloudy
8,09-01-2025,Eluru,NaN,64.0,Rainy
9,10-01-2025,Anakapalli,29.0,62.0,Sunny


## excel

In [158]:
df = pd.read_excel(r"L:\weather_data_XL.xlsx")
print(df)

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny


In [159]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [160]:
student={
    "name":["lokesh","ravi","varma"],
    "age":[30,40,15]
}


In [161]:
df=pd.DataFrame(student)
df

,name,age
0,lokesh,30
1,ravi,40
2,varma,15


In [162]:
df.to_csv("data.csv",index=False)

In [163]:
df.to_excel("new_xlsx.xlsx", sheet_name="Weather_data", index=False)

# Explore data

In [177]:
df.head()## first 5 rows

,name,age
0,lokesh,30
1,ravi,40
2,varma,15


In [178]:
df.head(8)

,name,age
0,lokesh,30
1,ravi,40
2,varma,15


In [179]:
df.tail()

,name,age
0,lokesh,30
1,ravi,40
2,varma,15


In [180]:
df.head(8)

,name,age
0,lokesh,30
1,ravi,40
2,varma,15


In [181]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str  
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes


In [151]:
df.shape

(3, 2)

In [152]:
df[4:8]

,name,reg


In [153]:
df.columns

Index(['name', 'reg'], dtype='str')

In [154]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [155]:
df.dtypes

name      str
reg     int64
dtype: object

# Missing Values

In [89]:
df.isnull() #chesk missing values

,Date,City,Temperature_C,Humidity_%,Condition
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,True,False,False
3,False,False,False,False,False
4,False,False,True,False,False
5,False,False,False,True,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,True,False,False
9,False,False,False,False,False


In [90]:
df. isnull().sum() #count missing values

Date             0
City             0
Temperature_C    3
Humidity_%       1
Condition        0
dtype: int64

In [91]:
df=pd.DataFrame({
    "name":["lokesh","kumar","varma"],
    "age":[23,43,None]
})
df
        

,name,age
0,lokesh,23.0
1,kumar,43.0
2,varma,NaN


# handilling missing values

In [108]:
df["age"]=df["age"].fillna(0)

In [104]:
df

,name,age
0,lokesh,23.0
1,kumar,43.0
2,varma,33.0


In [107]:
df["age"]=df["age"].fillna(df["age"].mean())
df

,name,age
0,lokesh,23.0
1,kumar,43.0
2,varma,33.0


In [110]:
df=df.dropna()

In [111]:
df

,name,age
0,lokesh,23.0
1,kumar,43.0
2,varma,33.0


# Duplicates

In [148]:
df=pd.DataFrame({
    "name":["lokesh","ravi","ravi"],
    "reg":[1012,1012,1012]
})
df

,name,reg
0,lokesh,1012
1,ravi,1012
2,ravi,1012


In [149]:
df.duplicated() #check dupplicates

0    False
1    False
2     True
dtype: bool

In [150]:
df.drop_duplicates()

,name,reg
0,lokesh,1012
1,ravi,1012


# statistics

In [124]:
df=pd.read_excel("L:\weather_data_XL.xlsx")
df

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\chede\AppData\Local\Temp\ipykernel_10812\2364700379.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df=pd.read_excel("L:\weather_data_XL.xlsx")


,Date,City,Temperature_C,Humidity_%,Condition
0,2025-01-01,Hyderbad,28,60,Sunny
1,2025-01-02,Hyderbad,29,62,Sunny
2,2025-01-03,Hyderbad,30,58,Cloudy
3,2025-01-04,Hyderbad,31,55,Cloudy
4,2025-01-05,Banglore,32,57,Rainy
5,2025-01-06,Banglore,33,59,Rainy
6,2025-01-07,Banglore,34,61,Sunny
7,2025-01-08,Banglore,32,63,Cloudy
8,2025-01-09,Vijayawada,31,64,Rainy
9,2025-01-10,Vijayawada,29,62,Sunny


In [126]:
df["Temperature_C"].std()

np.float64(1.911950719959998)

In [127]:
df["Temperature_C"].var()

np.float64(3.6555555555555554)

In [128]:
df["Temperature_C"].max()

np.int64(34)

In [129]:
df["Temperature_C"].min()

np.int64(28)

In [130]:
df["Temperature_C"].mean()

np.float64(30.9)

In [131]:
df["Temperature_C"].describe()

count    10.000000
mean     30.900000
std       1.911951
min      28.000000
25%      29.250000
50%      31.000000
75%      32.000000
max      34.000000
Name: Temperature_C, dtype: float64

In [133]:
df[df.Temperature_C==df.Temperature_C.max()]

,Date,City,Temperature_C,Humidity_%,Condition
6,2025-01-07,Banglore,34,61,Sunny


In [134]:
df.City[df.Temperature_C==df.Temperature_C.max()]

6    Banglore
Name: City, dtype: str

In [135]:
df.count()

Date             10
City             10
Temperature_C    10
Humidity_%       10
Condition        10
dtype: int64

In [136]:
df["City"].nunique()

3

In [138]:
df["City"].value_counts()

City
Hyderbad      4
Banglore      4
Vijayawada    2
Name: count, dtype: int64

# String Cleaning

In [140]:
df["City"]=df["City"].str.lower()
df

,Date,City,Temperature_C,Humidity_%,Condition
0,2025-01-01,hyderbad,28,60,Sunny
1,2025-01-02,hyderbad,29,62,Sunny
2,2025-01-03,hyderbad,30,58,Cloudy
3,2025-01-04,hyderbad,31,55,Cloudy
4,2025-01-05,banglore,32,57,Rainy
5,2025-01-06,banglore,33,59,Rainy
6,2025-01-07,banglore,34,61,Sunny
7,2025-01-08,banglore,32,63,Cloudy
8,2025-01-09,vijayawada,31,64,Rainy
9,2025-01-10,vijayawada,29,62,Sunny


In [141]:
df["City"]=df["City"].str.upper()
df

,Date,City,Temperature_C,Humidity_%,Condition
0,2025-01-01,HYDERBAD,28,60,Sunny
1,2025-01-02,HYDERBAD,29,62,Sunny
2,2025-01-03,HYDERBAD,30,58,Cloudy
3,2025-01-04,HYDERBAD,31,55,Cloudy
4,2025-01-05,BANGLORE,32,57,Rainy
5,2025-01-06,BANGLORE,33,59,Rainy
6,2025-01-07,BANGLORE,34,61,Sunny
7,2025-01-08,BANGLORE,32,63,Cloudy
8,2025-01-09,VIJAYAWADA,31,64,Rainy
9,2025-01-10,VIJAYAWADA,29,62,Sunny


In [142]:
df["City"]=df["City"].str.replace("HYDERBAD","CHENNAI")
df

,Date,City,Temperature_C,Humidity_%,Condition
0,2025-01-01,CHENNAI,28,60,Sunny
1,2025-01-02,CHENNAI,29,62,Sunny
2,2025-01-03,CHENNAI,30,58,Cloudy
3,2025-01-04,CHENNAI,31,55,Cloudy
4,2025-01-05,BANGLORE,32,57,Rainy
5,2025-01-06,BANGLORE,33,59,Rainy
6,2025-01-07,BANGLORE,34,61,Sunny
7,2025-01-08,BANGLORE,32,63,Cloudy
8,2025-01-09,VIJAYAWADA,31,64,Rainy
9,2025-01-10,VIJAYAWADA,29,62,Sunny
